### ISSUE TITLE
strange error

### ISSUE THREAD

**Issue by mpicci** [thorstel/Advent-of-Code-2017#1] opened 2018-09-23 18:16 UTC
Hi,
I'm getting this strange error in compilation

[ 96%] Building CXX object CMakeFiles/aoc17.dir/src/solution.cpp.o
[100%] Linking CXX executable aoc17
CMakeFiles/aoc17.dir/src/day15.cpp.o: In function `void solve<(Day)14>(std::istream&, std::ostream&)':
/usr/include/c++/7/thread:126: undefined reference to `pthread_create'
/usr/include/c++/7/thread:126: undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/aoc17.dir/build.make:796: recipe for target 'aoc17' failed
make[2]: *** [aoc17] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/aoc17.dir/all' failed
make[1]: *** [CMakeFiles/aoc17.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

Any clues?
I'm in ubuntu 18.04 with gcc-7.3

Thank you

**Comment by thorstel** [comment] 2018-09-23 19:31
Oh! I think you might have to include the -pthread linker flag for GCC explicitly. I added it to CMakeLists.txt, let me know if this solves your issue.

**Comment by mpicci** [comment] 2018-09-23 20:07
I'm still getting the same error.
On Day15.cpp.

**Comment by thorstel** [comment] 2018-09-23 20:44
I am not that familiar with cmake... `CXX_FLAGS` are probably only used for compile flags, so my change did not have any effect for your linker call.

I made another attempt with the proper `find_package(Threads)` now. I cannot reproduce this on my machine, you have to tell me whether this helps or not (make sure to execute cmake again).

**Comment by mpicci** [comment] 2018-09-23 21:16
Ok I'll check,
by the way, on day08 and runner I'm getting errors on INT_MIN INT_MAX not declared

**Comment by thorstel** [comment] 2018-09-24 07:04
Yeah, this is the problem when certain environments are trying to "help" you. For me a bunch of headers are included by default, so I do not necessarily notice if a source file is missing a pretty common include. Should be fixed now.

Also please let me know if the pthread reference is now fixed for you, thanks in advance :)

**Comment by mpicci** [comment] 2018-09-24 13:20
Hello,
This works
SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -pthread")
But still, I do not understand where threading is used!

**Comment by thorstel** [comment] 2018-09-24 13:24
Good, I guess this is solved then 😊

My solution for day 15 uses `std::async` to execute part 1 and 2 in parallel.

**Closed as completed by thorstel** 2018-09-24 13:24 UTC
